apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  completions: 2
  parallelism: 2
  backoffLimit: 20
  template:
    spec:
      containers:
      - name: job
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never