apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-resources
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 50