apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - type: Container
    default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 800m
      memory: 800Mi
    max:
      cpu: 1000m
      memory: 1000Mi
    min:
      cpu: 800m
      memory: 800Mi