apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-service-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-service-account
  template:
    metadata:
      labels:
        app:  deployment-service-account
    spec:
      serviceAccount: service-account
      containers:
      - name:  service-account
        image:  nginx
        resources: {}
        ports:
        - containerPort:  80
          name:  http
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-service-account
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-binding-service-account
subjects:
- kind: ServiceAccount
  name: service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-service-account
  apiGroup: rbac.authorization.k8s.io
