apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-secret
spec:
  selector:
    matchLabels:
      app: deployment-secret
  replicas: 1
  template:
    metadata:
      labels:
        app:  deployment-secret
    spec:
      containers:
      - name:  deployment-secret
        image:  mongo
        resources: {}
        envFrom:
          - secretRef:
              name: secret
        # env:
        #   - name: MONGO_INITDB_ROOT_USERNAME
        #     value: mongouser
        #   - name: MONGO_INITDB_ROOT_PASSWORD
        #     value: mongopwd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-secret-mapkey
spec:
  selector:
    matchLabels:
      app: deployment-secret-mapkey
  replicas: 1
  template:
    metadata:
      labels:
        app:  deployment-secret-mapkey
    spec:
      containers:
      - name:  deployment-secret-mapkey
        image:  mongo
        resources: {}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: secret
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: secret