# Install in the server
# https://www.tecmint.com/install-nfs-server-on-ubuntu/
# Install  in the machine 
# sudo apt install nfs-common
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-nfs
spec:
  selector:
    matchLabels:
      app: deployment-nfs
  replicas: 1
  template:
    metadata:
      labels:
        app:  deployment-nfs
    spec:
      containers:
      - name: deployment-nfs
        image: nginx
        resources: {}
        volumeMounts:
        - name: datafiles
          mountPath: /volume
      volumes:
        - name: datafiles
          nfs:
            path: /shared/deployment-nfs
            server: 192.168.234.124